### ISSUE TITLE
Parrot Architect amd64 iso - BE/FR Mirrors are down or not  responding ? 

### ISSUE THREAD

**Issue by TuxStory** [ParrotSec/debian-installer#1]
Hello

iso: Parrot-architect-5.1_amd64.iso
When I try to install parrot architect in a Virtualbox VM in French (Belgium & France), the repository mirrors do not respond.
The installer seems to be frozen afterwards.

- ftp.belnet.be - deb.parrot.sh - mirror.parrot.sh - azure.deb.parrot.sh - aws.deb.parrot.sh - [NOT WORKING]
- mirror.alyun.com [OK]
![VirtualBox_Parrot _09_11_2022_23_25_35](https://user-images.githubusercontent.com/68666318/200957945-33eb64b4-a2a8-45d4-ac7e-6215db1a1893.png)

I tried the installer with American English and the MIT repository and it works.

**Comment by ghost** [comment]
Try switch to the working mirror mirror.alyun.com during Parrot Architect installation in a VirtualBox VM in French-speaking regions.
